# Configurações gerais
params.customCSS = ["css/custom.css"]

# Menu
[menu]

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3
